version: '3'
services:
  app:
    image: php:8.2-apache
    ports:
      - 8080:80
      - 5173:5173
    volumes:
      - ./:/var/www/html/dusk-sample
    cap_add:
      - SYS_ADMIN
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - app
    privileged: true
